import { sql } from 'drizzle-orm'
import {
  check,
  integer,
  pgEnum,
  pgTable,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core'

import { timestamps } from './_common'
import { experiences } from './experiences'

/**
 * Slot status per ADR-0011. `closed` is a manual Vendor or admin
 * override that takes the slot off-market without deleting the row.
 */
export const slotStatusEnum = pgEnum('slot_status', ['open', 'sold_out', 'closed'])

/**
 * Materialised availability slots per ADR-0011. Generated by the
 * scheduled job (Vercel Cron) out to a rolling 6-month window from the
 * Experience's pattern config and skipping any region_closures.
 *
 * Schema invariants:
 *  - 0 ≤ capacity_taken ≤ capacity (CHECK)
 *  - one slot per (experience_id, start_at) (unique index)
 *
 * Cascade on experience delete is intentional — if the Experience is
 * archived/hard-deleted, the slots are too. Bookings reference slot_id
 * with onDelete:'restrict' (in db/schema/bookings.ts) so live Bookings
 * block Experience deletion.
 */
export const availabilitySlots = pgTable(
  'availability_slots',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    experienceId: uuid('experience_id')
      .references(() => experiences.id, { onDelete: 'cascade' })
      .notNull(),
    startAt: timestamp('start_at', { withTimezone: true }).notNull(),
    endAt: timestamp('end_at', { withTimezone: true }).notNull(),
    capacity: integer('capacity').notNull(),
    capacityTaken: integer('capacity_taken').default(0).notNull(),
    status: slotStatusEnum('status').default('open').notNull(),
    ...timestamps,
  },
  (t) => [
    check(
      'capacity_within_bounds',
      sql`${t.capacityTaken} >= 0 AND ${t.capacityTaken} <= ${t.capacity}`,
    ),
    check('positive_capacity', sql`${t.capacity} > 0`),
    check('slot_time_ordered', sql`${t.endAt} > ${t.startAt}`),
    uniqueIndex('availability_slots_experience_start').on(t.experienceId, t.startAt),
  ],
)

export type AvailabilitySlot = typeof availabilitySlots.$inferSelect
export type NewAvailabilitySlot = typeof availabilitySlots.$inferInsert
