import type { BlogContentMeta } from './types'

/**
 * The editorial blog plan: 40 SEO posts grounded in the real activity + region
 * registries (`lib/activities`, `lib/regions`) per ADR-0013's hub-and-spoke
 * model. Every `internalLinks` href resolves to a live route (validated in
 * tests/unit/content/blog-content.test.ts). Distribution is intent-weighted:
 * guides 10 / destinations 9 / adventure 9 / tips 8 / culture 4.
 *
 * Prose bodies live in `posts/<slug>.md`; meta descriptions in `excerpts.json`.
 */
export const BLOG_CONTENT_META: BlogContentMeta[] = [
  // ---------------------------------------------------------------- GUIDES (10)
  {
    slug: 'river-rafting-rishikesh-guide',
    title: 'The Complete Guide to River Rafting in Rishikesh',
    category: 'guides',
    targetKeyword: 'river rafting in rishikesh',
    cover: { kind: 'activity', slug: 'rafting', variant: 0 },
    internalLinks: ['/adventure/rafting-in-rishikesh', '/destinations/rishikesh', '/activities/rafting'],
    publishedOffsetDays: 9,
    wordTarget: 1600,
  },
  {
    slug: 'paragliding-bir-billing-beginners-guide',
    title: "Paragliding in Bir Billing: A Beginner's Complete Guide",
    category: 'guides',
    targetKeyword: 'paragliding in bir billing',
    cover: { kind: 'activity', slug: 'paragliding', variant: 0 },
    internalLinks: ['/adventure/paragliding-in-bir-billing', '/destinations/bir-billing', '/activities/paragliding'],
    publishedOffsetDays: 23,
    wordTarget: 1600,
  },
  {
    slug: 'scuba-diving-goa-first-timers-guide',
    title: "Scuba Diving in Goa: A First-Timer's Complete Guide",
    category: 'guides',
    targetKeyword: 'scuba diving in goa',
    cover: { kind: 'activity', slug: 'scuba-diving', variant: 0 },
    internalLinks: ['/adventure/scuba-diving-in-goa', '/destinations/goa', '/activities/scuba-diving'],
    publishedOffsetDays: 37,
    wordTarget: 1500,
  },
  {
    slug: 'hampta-pass-trek-guide',
    title: 'Hampta Pass Trek: The Complete Difficulty & Itinerary Guide',
    category: 'guides',
    targetKeyword: 'hampta pass trek',
    cover: { kind: 'activity', slug: 'trekking', variant: 0 },
    internalLinks: ['/adventure/trekking-in-manali', '/destinations/manali', '/activities/trekking'],
    publishedOffsetDays: 51,
    wordTarget: 1700,
  },
  {
    slug: 'adventure-sports-rishikesh-guide',
    title: 'A Complete Guide to Adventure Sports in Rishikesh',
    category: 'guides',
    targetKeyword: 'adventure sports in rishikesh',
    cover: { kind: 'activity', slug: 'rafting', variant: 3 },
    internalLinks: ['/destinations/rishikesh', '/adventure/rafting-in-rishikesh', '/activities/bungee-jumping'],
    publishedOffsetDays: 65,
    wordTarget: 1600,
  },
  {
    slug: 'bungee-jumping-india-guide',
    title: 'Bungee Jumping in India: Where to Jump, Costs & Safety',
    category: 'guides',
    targetKeyword: 'bungee jumping in india',
    cover: { kind: 'activity', slug: 'bungee-jumping', variant: 0 },
    internalLinks: ['/activities/bungee-jumping', '/destinations/rishikesh', '/safety'],
    publishedOffsetDays: 79,
    wordTarget: 1400,
  },
  {
    slug: 'trekking-himachal-pradesh-guide',
    title: 'The Complete Guide to Trekking in Himachal Pradesh',
    category: 'guides',
    targetKeyword: 'trekking in himachal pradesh',
    cover: { kind: 'activity', slug: 'trekking', variant: 1 },
    internalLinks: ['/activities/trekking', '/destinations/manali', '/destinations/kasol'],
    publishedOffsetDays: 93,
    wordTarget: 1700,
  },
  {
    slug: 'wildlife-safari-india-guide',
    title: "Wildlife Safari in India: A Beginner's Planning Guide",
    category: 'guides',
    targetKeyword: 'wildlife safari in india',
    cover: { kind: 'activity', slug: 'safari', variant: 0 },
    internalLinks: ['/activities/safari', '/destinations'],
    publishedOffsetDays: 107,
    wordTarget: 1500,
  },
  {
    slug: 'skiing-india-auli-guide',
    title: 'Skiing in India: A Complete Guide to Auli and Beyond',
    category: 'guides',
    targetKeyword: 'skiing in india',
    cover: { kind: 'activity', slug: 'skiing', variant: 0 },
    internalLinks: ['/destinations/auli', '/activities/skiing'],
    publishedOffsetDays: 121,
    wordTarget: 1400,
  },
  {
    slug: 'himalayan-camping-beginners-guide',
    title: "Himalayan Camping: A Complete Beginner's Guide",
    category: 'guides',
    targetKeyword: 'himalayan camping',
    cover: { kind: 'activity', slug: 'camping', variant: 0 },
    internalLinks: ['/activities/camping', '/adventure/camping-in-bir-billing', '/destinations/bir-billing'],
    publishedOffsetDays: 135,
    wordTarget: 1500,
  },

  // ---------------------------------------------------------- DESTINATIONS (9)
  {
    slug: 'best-things-to-do-rishikesh',
    title: '12 Best Things to Do in Rishikesh for Adventure Lovers',
    category: 'destinations',
    targetKeyword: 'things to do in rishikesh',
    cover: { kind: 'region', slug: 'rishikesh' },
    internalLinks: ['/destinations/rishikesh', '/adventure/rafting-in-rishikesh', '/activities/bungee-jumping'],
    publishedOffsetDays: 5,
    wordTarget: 1600,
  },
  {
    slug: 'bir-billing-travel-guide',
    title: "Bir Billing Travel Guide: India's Paragliding Capital",
    category: 'destinations',
    targetKeyword: 'bir billing travel guide',
    cover: { kind: 'region', slug: 'bir-billing' },
    internalLinks: ['/destinations/bir-billing', '/adventure/paragliding-in-bir-billing', '/activities/camping'],
    publishedOffsetDays: 19,
    wordTarget: 1500,
  },
  {
    slug: 'things-to-do-manali-adventure',
    title: 'Best Things to Do in Manali: The Adventure Edition',
    category: 'destinations',
    targetKeyword: 'things to do in manali',
    cover: { kind: 'region', slug: 'manali' },
    internalLinks: ['/destinations/manali', '/adventure/trekking-in-manali', '/activities/paragliding'],
    publishedOffsetDays: 33,
    wordTarget: 1600,
  },
  {
    slug: 'goa-adventure-watersports-guide',
    title: 'Goa Beyond the Beaches: An Adventure & Watersports Guide',
    category: 'destinations',
    targetKeyword: 'goa watersports',
    cover: { kind: 'region', slug: 'goa' },
    internalLinks: ['/destinations/goa', '/adventure/scuba-diving-in-goa', '/activities/scuba-diving'],
    publishedOffsetDays: 47,
    wordTarget: 1500,
  },
  {
    slug: 'leh-ladakh-adventure-guide',
    title: 'Leh-Ladakh Adventure Guide: What to Do and When to Go',
    category: 'destinations',
    targetKeyword: 'leh ladakh adventure',
    cover: { kind: 'region', slug: 'leh-ladakh' },
    internalLinks: ['/destinations/leh-ladakh', '/activities/trekking'],
    publishedOffsetDays: 61,
    wordTarget: 1600,
  },
  {
    slug: 'spiti-valley-adventure-guide',
    title: 'Spiti Valley: The Ultimate Adventure Travel Guide',
    category: 'destinations',
    targetKeyword: 'spiti valley travel guide',
    cover: { kind: 'region', slug: 'spiti' },
    internalLinks: ['/destinations/spiti', '/activities/trekking', '/activities/camping'],
    publishedOffsetDays: 75,
    wordTarget: 1600,
  },
  {
    slug: 'kasol-parvati-valley-trekkers-guide',
    title: "Kasol and Parvati Valley: A Trekker's Guide",
    category: 'destinations',
    targetKeyword: 'kasol parvati valley',
    cover: { kind: 'region', slug: 'kasol' },
    internalLinks: ['/destinations/kasol', '/activities/trekking', '/activities/camping'],
    publishedOffsetDays: 89,
    wordTarget: 1400,
  },
  {
    slug: 'andaman-islands-watersports-diving',
    title: 'Andaman Islands: Best Watersports and Diving Spots',
    category: 'destinations',
    targetKeyword: 'andaman watersports',
    cover: { kind: 'region', slug: 'andaman' },
    internalLinks: ['/destinations/andaman', '/activities/scuba-diving'],
    publishedOffsetDays: 103,
    wordTarget: 1500,
  },
  {
    slug: 'lonavala-adventure-guide',
    title: 'Lonavala Adventure Guide: Treks, Camps and Monsoon Escapes',
    category: 'destinations',
    targetKeyword: 'lonavala adventure',
    cover: { kind: 'region', slug: 'lonavala' },
    internalLinks: ['/destinations/lonavala', '/activities/trekking', '/activities/camping'],
    publishedOffsetDays: 117,
    wordTarget: 1400,
  },

  // ------------------------------------------------------------- ADVENTURE (9)
  {
    slug: 'river-rafting-grades-explained',
    title: 'River Rafting Grades Explained: From Grade I to V',
    category: 'adventure',
    targetKeyword: 'river rafting grades',
    cover: { kind: 'activity', slug: 'rafting', variant: 1 },
    internalLinks: ['/activities/rafting', '/adventure/rafting-in-rishikesh'],
    publishedOffsetDays: 11,
    wordTarget: 1300,
  },
  {
    slug: 'tandem-paragliding-first-flight',
    title: 'Tandem Paragliding: What Your First Flight Is Really Like',
    category: 'adventure',
    targetKeyword: 'tandem paragliding first time',
    cover: { kind: 'activity', slug: 'paragliding', variant: 2 },
    internalLinks: ['/adventure/paragliding-in-bir-billing', '/activities/paragliding'],
    publishedOffsetDays: 25,
    wordTarget: 1200,
  },
  {
    slug: 'padi-discover-scuba-vs-fun-dive',
    title: 'PADI Discover Scuba vs Fun Dive: Which Should You Pick?',
    category: 'adventure',
    targetKeyword: 'discover scuba vs fun dive',
    cover: { kind: 'activity', slug: 'scuba-diving', variant: 2 },
    internalLinks: ['/adventure/scuba-diving-in-goa', '/activities/scuba-diving'],
    publishedOffsetDays: 39,
    wordTarget: 1300,
  },
  {
    slug: 'whitewater-kayaking-beginners',
    title: 'Whitewater Kayaking for Beginners: Your First Lesson',
    category: 'adventure',
    targetKeyword: 'whitewater kayaking for beginners',
    cover: { kind: 'activity', slug: 'kayaking', variant: 0 },
    internalLinks: ['/adventure/kayaking-in-rishikesh', '/activities/kayaking'],
    publishedOffsetDays: 53,
    wordTarget: 1200,
  },
  {
    slug: 'rock-climbing-india-beginners',
    title: 'Rock Climbing in India: Best Crags for Beginners',
    category: 'adventure',
    targetKeyword: 'rock climbing in india',
    cover: { kind: 'activity', slug: 'rock-climbing', variant: 0 },
    internalLinks: ['/activities/rock-climbing', '/destinations'],
    publishedOffsetDays: 67,
    wordTarget: 1300,
  },
  {
    slug: 'first-himalayan-trek-what-to-expect',
    title: 'What to Expect on Your First Multi-Day Himalayan Trek',
    category: 'adventure',
    targetKeyword: 'first himalayan trek',
    cover: { kind: 'activity', slug: 'trekking', variant: 2 },
    internalLinks: ['/activities/trekking', '/adventure/trekking-in-manali'],
    publishedOffsetDays: 81,
    wordTarget: 1400,
  },
  {
    slug: 'bungee-jumping-rishikesh-worth-it',
    title: 'Bungee Jumping in Rishikesh: Is It Worth It?',
    category: 'adventure',
    targetKeyword: 'bungee jumping rishikesh',
    cover: { kind: 'activity', slug: 'bungee-jumping', variant: 2 },
    internalLinks: ['/destinations/rishikesh', '/activities/bungee-jumping'],
    publishedOffsetDays: 95,
    wordTarget: 1200,
  },
  {
    slug: 'wildlife-safari-etiquette',
    title: 'Wildlife Safari Etiquette: Spot More, Disturb Less',
    category: 'adventure',
    targetKeyword: 'wildlife safari etiquette',
    cover: { kind: 'activity', slug: 'safari', variant: 2 },
    internalLinks: ['/activities/safari', '/destinations'],
    publishedOffsetDays: 109,
    wordTarget: 1200,
  },
  {
    slug: 'himalayan-camping-bir-billing',
    title: 'A Night Under the Stars: Himalayan Camping in Bir Billing',
    category: 'adventure',
    targetKeyword: 'camping in bir billing',
    cover: { kind: 'activity', slug: 'camping', variant: 2 },
    internalLinks: ['/adventure/camping-in-bir-billing', '/destinations/bir-billing'],
    publishedOffsetDays: 123,
    wordTarget: 1300,
  },

  // ------------------------------------------------------------------- TIPS (8)
  {
    slug: 'what-to-wear-river-rafting-india',
    title: 'What to Wear for River Rafting in India (by Season)',
    category: 'tips',
    targetKeyword: 'what to wear for river rafting',
    cover: { kind: 'activity', slug: 'rafting', variant: 4 },
    internalLinks: ['/activities/rafting', '/adventure/rafting-in-rishikesh'],
    publishedOffsetDays: 13,
    wordTarget: 1100,
  },
  {
    slug: 'train-for-himalayan-trek-8-weeks',
    title: 'How to Train for a Himalayan Trek in 8 Weeks',
    category: 'tips',
    targetKeyword: 'how to train for a himalayan trek',
    cover: { kind: 'activity', slug: 'trekking', variant: 3 },
    internalLinks: ['/activities/trekking', '/destinations/manali'],
    publishedOffsetDays: 27,
    wordTarget: 1300,
  },
  {
    slug: 'himalayas-adventure-packing-list',
    title: 'Adventure Travel Packing List for the Indian Himalayas',
    category: 'tips',
    targetKeyword: 'himalaya adventure packing list',
    cover: { kind: 'activity', slug: 'camping', variant: 1 },
    internalLinks: ['/destinations/manali', '/activities/trekking'],
    publishedOffsetDays: 41,
    wordTarget: 1200,
  },
  {
    slug: 'avoid-altitude-sickness-himalayas',
    title: 'How to Avoid Altitude Sickness on High-Himalaya Trips',
    category: 'tips',
    targetKeyword: 'avoid altitude sickness',
    cover: { kind: 'region', slug: 'leh-ladakh' },
    internalLinks: ['/destinations/leh-ladakh', '/destinations/spiti', '/safety'],
    publishedOffsetDays: 55,
    wordTarget: 1300,
  },
  {
    slug: 'best-time-indian-adventure-destinations',
    title: 'The Best Time to Visit Each Indian Adventure Destination',
    category: 'tips',
    targetKeyword: 'best time to visit india adventure',
    cover: { kind: 'activity', slug: 'trekking', variant: 4 },
    internalLinks: ['/destinations', '/destinations/rishikesh', '/destinations/goa'],
    publishedOffsetDays: 69,
    wordTarget: 1300,
  },
  {
    slug: 'adventure-sports-travel-insurance-india',
    title: 'Do You Need Travel Insurance for Adventure Sports in India?',
    category: 'tips',
    targetKeyword: 'adventure sports travel insurance india',
    cover: { kind: 'activity', slug: 'trekking', variant: 5 },
    internalLinks: ['/safety', '/activities/trekking'],
    publishedOffsetDays: 83,
    wordTarget: 1100,
  },
  {
    slug: 'choose-safe-adventure-operator',
    title: 'How to Choose a Safe, Certified Adventure Operator',
    category: 'tips',
    targetKeyword: 'how to choose adventure operator',
    cover: { kind: 'activity', slug: 'rafting', variant: 2 },
    internalLinks: ['/safety', '/activities/rafting'],
    publishedOffsetDays: 97,
    wordTarget: 1200,
  },
  {
    slug: 'family-adventure-trips-india',
    title: 'Family Adventure Trips in India: Picking Activities by Age',
    category: 'tips',
    targetKeyword: 'family adventure trips india',
    cover: { kind: 'activity', slug: 'camping', variant: 3 },
    internalLinks: ['/destinations', '/activities/camping', '/activities/safari'],
    publishedOffsetDays: 111,
    wordTarget: 1300,
  },

  // ---------------------------------------------------------------- CULTURE (4)
  {
    slug: 'spiritual-rishikesh-yoga-ganga-aarti',
    title: 'The Spiritual Side of Rishikesh: Yoga and the Ganga Aarti',
    category: 'culture',
    targetKeyword: 'rishikesh yoga ganga aarti',
    cover: { kind: 'region', slug: 'rishikesh' },
    internalLinks: ['/destinations/rishikesh', '/activities/rafting'],
    publishedOffsetDays: 15,
    wordTarget: 1100,
  },
  {
    slug: 'himachal-local-food-guide',
    title: 'Local Food to Try in Himachal on Your Adventure Trip',
    category: 'culture',
    targetKeyword: 'himachal local food',
    cover: { kind: 'region', slug: 'manali' },
    internalLinks: ['/destinations/manali', '/destinations/kasol'],
    publishedOffsetDays: 43,
    wordTarget: 1000,
  },
  {
    slug: 'goa-festivals-travel-guide',
    title: 'Festivals Worth Planning Your Goa Trip Around',
    category: 'culture',
    targetKeyword: 'goa festivals',
    cover: { kind: 'region', slug: 'goa' },
    internalLinks: ['/destinations/goa', '/activities/scuba-diving'],
    publishedOffsetDays: 71,
    wordTarget: 1100,
  },
  {
    slug: 'tibetan-culture-bir-billing',
    title: 'Tibetan Culture in Bir Billing: Monasteries and Momos',
    category: 'culture',
    targetKeyword: 'bir billing tibetan culture',
    cover: { kind: 'region', slug: 'bir-billing' },
    internalLinks: ['/destinations/bir-billing', '/adventure/paragliding-in-bir-billing'],
    publishedOffsetDays: 99,
    wordTarget: 1100,
  },
]
